  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Research"
  weight = 200
  identifier = "research"
  url = "/research/"
  
#  [[main]]
#  name = "Opportunities"
#  weight = 300
#  identifier = "opportunities"
#  url = "/opportunities/"
  
  [[main]]
  name = "Media" 
  weight = 400
  identifier = "media"
  url = "/media/"
  
  [[main]]
  name = "Publications"
  weight = 500
  identifier = "publications"
  url = "/publications/"  
  
  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"
